# Generated by Django 5.1.4 on 2025-01-02 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0004_alter_exerciselevel_user_alter_skill_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_level', models.PositiveIntegerField(verbose_name='目標級別')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='目標完成日期')),
                ('is_achieved', models.BooleanField(default=False, verbose_name='是否達成')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.skill', verbose_name='技能')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '健身目標',
                'verbose_name_plural': '健身目標',
            },
        ),
    ]
