# Generated by Django 5.1.1 on 2024-12-31 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': '評論', 'verbose_name_plural': '評論'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['created_at'], 'verbose_name': '讚', 'verbose_name_plural': '讚'},
        ),
    ]
