# Generated by Django 5.1.1 on 2024-12-31 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名稱')),
                ('category', models.CharField(max_length=50, verbose_name='類別')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.PositiveIntegerField(verbose_name='級別')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.skill', verbose_name='技能')),
            ],
        ),
    ]
