# Generated by Django 5.1.1 on 2024-12-31 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciselevel',
            options={'verbose_name': '級別', 'verbose_name_plural': '級別'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': '技能', 'verbose_name_plural': '技能'},
        ),
        migrations.AlterUniqueTogether(
            name='exerciselevel',
            unique_together={('skill', 'level_number')},
        ),
    ]
