# Generated by Django 5.1.1 on 2024-12-31 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名稱')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('progression_level', models.IntegerField(verbose_name='進階級別')),
                ('sets', models.PositiveIntegerField(verbose_name='組數')),
                ('reps_per_set', models.PositiveIntegerField(verbose_name='每組次數')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise', verbose_name='動作')),
            ],
        ),
    ]
