# Generated by Django 5.1.4 on 2025-01-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_alter_exercise_user_alter_workoutsession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='是否完成'),
        ),
    ]
